//---------------------------------------------------------------------------

#ifndef ApertureControlProgram_mainH
#define ApertureControlProgram_mainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include "CommPort.h"
#include <ComCtrls.hpp>
#include <Dialogs.hpp>
#include <ExtCtrls.hpp>
#include <ImgList.hpp>
#include <Menus.hpp>
#include <ToolWin.hpp>
#include <Buttons.hpp>
//---------------------------------------------------------------------------
class TMainForm : public TForm
{
__published:	// IDE-managed Components
	TToolBar *ToolBar1;
	TToolButton *ToolButton3;
	TToolButton *TB_LoadBlp;
	TToolButton *ToolButton1;
	TToolButton *TB_LoadSar;
	TToolButton *ToolButton5;
	TToolButton *TB_SaveControl;
	TToolButton *ToolButton7;
	TToolButton *TB_SaveTesting;
	TToolButton *ToolButton2;
	TToolButton *TB_LoadControl;
	TToolButton *ToolButton4;
	TToolButton *TB_LoadTesting;
	TToolButton *ToolButton6;
	TToolButton *TB_About;
	TTimer *NIDAQmxTimer;
	TOpenDialog *OpenDialog1;
	TSaveDialog *SaveDialog1;
	TImageList *ImageList1;
	TCommPort *CommPort1;
	TSpeedButton *SB_OnOff;
	TGroupBox *GB_AvailableCom;
	TButton *B_AvailableCom;
	TPageControl *PC_Main;
	TTabSheet *Tsh_Control;
	TScrollBox *SB_Data2;
	TTabSheet *Sar_invisible;
	TLabel *L_H;
	TLabel *L_M;
	TLabel *L_S;
	TStaticText *StaticText4;
	TPanel *P_SystemTime;
	TStaticText *StaticText3;
	TPanel *P_WorkTime;
	TTimer *SystemTimer;
	TTimer *WorkTimer;
	TGroupBox *GroupBox1;
	TCheckBox *CheckBox1;
	TComboBox *ComboBox1;
	TGroupBox *GroupBox2;
	TCheckBox *CheckBox2;
	TComboBox *ComboBox2;
	TGroupBox *GroupBox3;
	TCheckBox *CheckBox3;
	TComboBox *ComboBox3;
	TCheckBox *CheckBox9;
	TButton *Button1;
	TGroupBox *GroupBox5;
	TCheckBox *CheckBox5;
	TRadioButton *RadioButton3;
	TRadioButton *RadioButton4;
	TListBox *LB_AvailableCom;
	TGroupBox *GB_Commands;
	TLabel *Label16;
	TButton *B_Ready;
	TButton *B_Send;
	TComboBox *CB_ComNum;
	TLabeledEdit *LE_V;
	TLabeledEdit *LE_f;
	TLabeledEdit *LE_Fi;
	TLabeledEdit *LE_D;
	TMainMenu *MainMenu;
	TMenuItem *File;
	TMenuItem *LoadBlp;
	TMenuItem *LoadSar;
	TMenuItem *N1;
	TMenuItem *SaveCtr;
	TMenuItem *SaveTst;
	TMenuItem *N2;
	TMenuItem *LoadCtr;
	TMenuItem *LoadTst;
	TMenuItem *N3;
	TMenuItem *Exit;
	TMenuItem *Help;
	TMenuItem *HelpAboutProg;
	TMenuItem *HelpAboutItem;
	TTabSheet *TSh_Service;
	TPageControl *PC_Service;
	TTabSheet *TSh_VIP;
	TTabSheet *TSh_FRLP_Control;
	TTabSheet *h_FRLP_Testing;
	TTabSheet *TSh_PRM_PRD;
	TTabSheet *TSh_UU;
	TTabSheet *TSh_BS;
	TTabSheet *TSh_VK_PRM;
	TTabSheet *TSh_VK_PRD;
	TCheckBox *CheckBox13;
	TGroupBox *GroupBox6;
	TCheckBox *CheckBox6;
	TRadioButton *RadioButton5;
	TRadioButton *RadioButton6;
	TGroupBox *GroupBox7;
	TCheckBox *CheckBox7;
	TRadioButton *RadioButton7;
	TRadioButton *RadioButton8;
	TGroupBox *GroupBox8;
	TCheckBox *CheckBox8;
	TRadioButton *RadioButton13;
	TRadioButton *RadioButton14;
	TGroupBox *GB_Command3;
	TStaticText *StaticText10;
	TStaticText *StaticText11;
	TEdit *E_Command3;
	TEdit *E_Command3_0;
	TStaticText *StaticText49;
	TComboBox *CB_Command3_1;
	TCheckBox *ChB_Command3;
	TStaticText *StaticText13;
	TEdit *E_Command4;
	TStaticText *StaticText15;
	TEdit *E_Command5;
	TComboBox *CB_SignC;
	TComboBox *CB_Shift;
	TStaticText *StaticText14;
	TGroupBox *GB_Command7;
	TCheckBox *ChB_Command7;
	TComboBox *CB_Command7;
	TCheckBox *CheckBox16;
	TScrollBox *ScrollBox2;
	TCheckBox *CheckBox17;
	TGroupBox *GB_Com3;
	TCheckBox *ChB_Com3;
	TStaticText *StaticText16;
	TStaticText *StaticText17;
	TEdit *E_Com3_0;
	TEdit *E_Com3;
	TStaticText *StaticText51;
	TComboBox *CB_Com3_1;
	TStaticText *StaticText19;
	TEdit *E_Com4;
	TStaticText *StaticText21;
	TEdit *E_Com5;
	TComboBox *CB_SignT;
	TStaticText *StaticText18;
	TComboBox *CB_Shift_;
	TGroupBox *GB_Com6;
	TCheckBox *ChB_Com6;
	TComboBox *CB_Com6;
	TGroupBox *GB_Com7;
	TCheckBox *ChB_Com7;
	TComboBox *CB_Com7;
	TGroupBox *GB_Com8;
	TCheckBox *ChB_Com8;
	TComboBox *CB_Com8;
	TGroupBox *GB_Com9;
	TCheckBox *ChB_Com9;
	TComboBox *CB_Com9;
	TGroupBox *GB_Com10;
	TLabel *Label8;
	TCheckBox *ChB_Com10;
	TComboBox *CB_Com10;
	TStaticText *StaticText22;
	TGroupBox *GB_Com11;
	TLabel *Label2;
	TCheckBox *ChB_Com11;
	TComboBox *CB_Com11;
	TStaticText *StaticText23;
	TGroupBox *GB_Com13;
	TLabel *Label1;
	TLabel *Label3;
	TLabel *Label4;
	TLabel *Label5;
	TCheckBox *ChB_Com13;
	TComboBox *CB_Output;
	TComboBox *CB_AuxOut;
	TEdit *E_OutFreq;
	TScrollBox *ScrollBox3;
	TCheckBox *CheckBox18;
	TGroupBox *GroupBox9;
	TCheckBox *CheckBox10;
	TComboBox *ComboBox5;
	TGroupBox *GroupBox10;
	TCheckBox *CheckBox11;
	TComboBox *ComboBox6;
	TGroupBox *GroupBox13;
	TCheckBox *CheckBox14;
	TRadioButton *RadioButton9;
	TRadioButton *RadioButton10;
	TGroupBox *GroupBox14;
	TCheckBox *CheckBox15;
	TRadioButton *RadioButton11;
	TRadioButton *RadioButton12;
	TGroupBox *GroupBox36;
	TCheckBox *CheckBox36;
	TEdit *Edit32;
	TGroupBox *GroupBox37;
	TCheckBox *CheckBox37;
	TEdit *Edit33;
	TScrollBox *ScrollBox1;
	TCheckBox *CheckBox19;
	TGroupBox *GroupBox4;
	TCheckBox *CheckBox4;
	TRadioButton *RadioButton1;
	TRadioButton *RadioButton2;
	TGroupBox *GroupBox12;
	TCheckBox *CheckBox20;
	TComboBox *ComboBox4;
	TGroupBox *GroupBox15;
	TCheckBox *CheckBox21;
	TComboBox *ComboBox7;
	TGroupBox *GroupBox16;
	TCheckBox *CheckBox22;
	TComboBox *ComboBox8;
	TStatusBar *StatusBar1;
	TMemo *M_Debug;
	TGroupBox *GB_Message;
	TEdit *E_EnterComment;
	TMemo *M_Log;
	TStaticText *StaticText6;
	TStaticText *StaticText7;
	TButton *B_Enter;
	TCheckBox *ChB_Log;
	TPanel *P_FRLP;
	TLabel *Label6;
	TPanel *P_PRM;
	TLabel *Label7;
	TPanel *P_PRD;
	TLabel *Label9;
	TPanel *P_BS;
	TLabel *Label10;
	TPanel *P_Zahvat;
	TLabel *Label11;
	TPanel *P_ACP;
	TLabel *Label12;
	TPanel *P_CAP;
	TLabel *Label13;
	TPanel *P_PLIS;
	TPanel *P_VklSint;
	TLabel *Label15;
	TPanel *P_VK_PRM;
	TLabel *Label17;
	TPanel *P_VK_PRD1;
	TLabel *Label18;
	TPanel *P_VK_PRD2;
	TLabel *Label14;
	TLabel *Label20;
	TLabel *Label19;
	TLabel *Label21;
	TButton *Button2;
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall B_AvailableComClick(TObject *Sender);
	void __fastcall TB_AboutClick(TObject *Sender);
	void __fastcall HelpAboutProgClick(TObject *Sender);
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall B_EnterClick(TObject *Sender);
	void __fastcall ChB_LogClick(TObject *Sender);
	void __fastcall WorkTimerTimer(TObject *Sender);
	void __fastcall SB_OnOffClick(TObject *Sender);
	void __fastcall SystemTimerTimer(TObject *Sender);
	void __fastcall ExitClick(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall E_Command3Change(TObject *Sender);
	void __fastcall E_Command3Exit(TObject *Sender);
	void __fastcall E_Command3KeyPress(TObject *Sender, wchar_t &Key);
	void __fastcall E_Command3_0Change(TObject *Sender);
	void __fastcall E_Command3_0Exit(TObject *Sender);
	void __fastcall CB_Command3_1Change(TObject *Sender);
	void __fastcall CB_SignCKeyPress(TObject *Sender, wchar_t &Key);
	void __fastcall CB_ShiftChange(TObject *Sender);
	void __fastcall E_Command4Change(TObject *Sender);
	void __fastcall E_Command4Exit(TObject *Sender);
	void __fastcall CB_SignCChange(TObject *Sender);
	void __fastcall CB_SignCExit(TObject *Sender);
	void __fastcall E_Command5Change(TObject *Sender);
	void __fastcall E_Command5Exit(TObject *Sender);
	void __fastcall CB_Command7Change(TObject *Sender);
	void __fastcall CB_Command7Exit(TObject *Sender);
	void __fastcall E_Com3Change(TObject *Sender);
	void __fastcall E_Com3Exit(TObject *Sender);
	void __fastcall CB_Com3_1Change(TObject *Sender);
	void __fastcall E_Com3_0Change(TObject *Sender);
	void __fastcall E_Com3_0Exit(TObject *Sender);
	void __fastcall CB_Shift_Change(TObject *Sender);
	void __fastcall CB_ShiftExit(TObject *Sender);
	void __fastcall CB_Shift_Exit(TObject *Sender);
	void __fastcall E_Com4Change(TObject *Sender);
	void __fastcall E_Com4Exit(TObject *Sender);
	void __fastcall E_Com5Change(TObject *Sender);
	void __fastcall E_Com5Exit(TObject *Sender);
	void __fastcall CB_SignTChange(TObject *Sender);
	void __fastcall CB_SignTExit(TObject *Sender);
	void __fastcall CB_Com6Change(TObject *Sender);
	void __fastcall CB_Com7Change(TObject *Sender);
	void __fastcall CB_Com8Change(TObject *Sender);
	void __fastcall CB_Com9Change(TObject *Sender);
	void __fastcall CB_Com10Change(TObject *Sender);
	void __fastcall CB_Com11Change(TObject *Sender);
	void __fastcall CB_OutputChange(TObject *Sender);
	void __fastcall CB_AuxOutChange(TObject *Sender);
	void __fastcall E_OutFreqChange(TObject *Sender);
	void __fastcall TB_LoadBlpClick(TObject *Sender);
	void __fastcall TB_LoadSarClick(TObject *Sender);
	void __fastcall TB_SaveControlClick(TObject *Sender);
	void __fastcall TB_SaveTestingClick(TObject *Sender);
	void __fastcall TB_LoadControlClick(TObject *Sender);
	void __fastcall TB_LoadTestingClick(TObject *Sender);
	void __fastcall B_ReadyClick(TObject *Sender);
	void __fastcall E_Command5KeyPress(TObject *Sender, wchar_t &Key);
	void __fastcall Button2Click(TObject *Sender);

private:	// User declarations
	String BlpFName;
	String SarFName;
public:		// User declarations
	__fastcall TMainForm(TComponent* Owner);
	void __fastcall TMainForm::SearchCOMPorts(void);
	String My_Patch;
	String logFname;
	void __fastcall TMainForm::AddSaveLog(String comment);
	void __fastcall TMainForm::ButtonsOn(void);
	bool TMainForm::IsValidInt(int min, int max, String value, String EdIzm);
	void TMainForm::ShowError(int ErrorNum, float Par1, float Par2, String Par3);
	void __fastcall TMainForm::BanCharInput(char &Key);
    bool __fastcall TMainForm::SetDevP0P1Data(const char *Config0, const char *Config1);
	float __fastcall TMainForm::GetDevACDData(const char *Config);
	String TMainForm::RoundValue(float delta, float fvalue);
	void __fastcall TMainForm::ResetBPControl(void);
	void __fastcall TMainForm::InitBPControl(void);
	bool TMainForm::IsValid(float min, float max, String value, String EdIzm);
	void __fastcall TMainForm::ResetBPTesting(void);
	void __fastcall TMainForm::InitBPTesting(void);
	void __fastcall TMainForm::Fvco_OD(void);
	void __fastcall TMainForm::Ndevider(void);
	void __fastcall TMainForm::UpdateRegister0(void);
	void __fastcall TMainForm::UpdateRegister1(void);
	void __fastcall TMainForm::UpdateRegister4(void);
	void __fastcall TMainForm::UpdateAllRegisters(void);
	void __fastcall TMainForm::AlgorithmBS(void);
	bool __fastcall TMainForm::DigitalLineWrite(int LineNumber, int DValue);
	void TMainForm::ClearDevs(void);
	void TMainForm::DevToP0P1(unsigned char* DevP0, unsigned char* DevP1);
	void __fastcall TMainForm::SetDevNumber(int device);
};
//---------------------------------------------------------------------------
extern PACKAGE TMainForm *MainForm;
//---------------------------------------------------------------------------
#endif

