//---------------------------------------------------------------------------

#ifndef ControlTesting_MainH
#define ControlTesting_MainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Buttons.hpp>
#include <Menus.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <ToolWin.hpp>
#include <Dialogs.hpp>
#include <ImgList.hpp>
//---------------------------------------------------------------------------
class TMain_Form : public TForm
{
__published:	// IDE-managed Components
  TGroupBox *GB_Mode;
  TRadioButton *RB_Control;
  TRadioButton *RB_Testing;
  TStaticText *StaticText1;
  TPanel *Panel1;
  TPanel *Panel2;
  TPanel *Panel3;
  TPanel *Panel4;
  TGroupBox *GroupBox2;
  TButton *btnNew;
  TButton *btnSave;
  TButton *btnLoad;
  TButton *btnSaveAs;
  TGroupBox *GroupBox3;
  TButton *B_Ready;
  TButton *B_Send;
  TPanel *P_SystemTime;
  TPanel *P_WorkTime;
  TSpeedButton *SB_OnOff;
  TTimer *SystemTimer;
  TTimer *WorkTimer;
  TLabel *L_S;
  TLabel *L_M;
  TLabel *L_H;
  TStaticText *StaticText3;
  TStaticText *StaticText4;
  TSaveDialog *SaveDialog;
  TGroupBox *GB_Message;
  TEdit *E_EnterComment;
  TMemo *M_Log;
  TStaticText *StaticText6;
  TStaticText *StaticText7;
  TButton *B_Enter;
  TPageControl *PC_Main;
  TTabSheet *BT;
  TListView *LVScan;
  TGroupBox *GroupBox1;
  TBitBtn *B_AddBT;
  TBitBtn *B_DeleteBT;
  TTabSheet *RLS1;
  TListView *LV_Sar1;
  TGroupBox *GroupBox4;
  TBitBtn *B_AddSar1;
  TBitBtn *B_DeleteSar1;
  TStaticText *StaticText2;
  TStaticText *StaticText5;
  TGroupBox *GroupBox5;
  TBitBtn *B_AddSar2;
  TBitBtn *B_DeleteSar2;
  TListView *LV_Sar2;
  TStaticText *StaticText8;
  TListView *LV_Sar3;
  TStaticText *StaticText9;
  TGroupBox *GroupBox6;
  TBitBtn *B_AddSar3;
  TBitBtn *B_DeleteSar3;
  TGroupBox *GroupBox7;
  TBitBtn *B_AddSar4;
  TBitBtn *B_DeleteSar4;
  TListView *LV_Sar4;
  TTabSheet *TabSheet1;
  TTabSheet *TabSheet2;
  TScrollBox *ScrollBox1;
  TToolBar *ToolBar1;
  TToolButton *ToolButton1;
  TToolButton *TB_LoadBlp;
  TToolButton *ToolButton3;
  TToolButton *TB_LoadSar;
  TToolButton *ToolButton5;
  TToolButton *TB_SaveControl;
  TToolButton *ToolButton7;
  TToolButton *TB_SaveTesting;
  TToolButton *ToolButton9;
  TToolButton *TB_Exit;
  TToolButton *ToolButton11;
  TToolButton *BT_About;
  TOpenDialog *OpenDialog;
  TOpenDialog *OpenDialog1;
  TImageList *ImageList1;
  TToolButton *ToolButton2;
  TMainMenu *MainMenu1;
  TMenuItem *File;
  TStatusBar *StatusBar1;
  TGroupBox *GB_Command1;
  TCheckBox *ChB_Command1;
  TComboBox *CB_Command1;
  TGroupBox *GB_Command2;
  TCheckBox *ChB_Command2;
  TEdit *E_Command2;
  TGroupBox *GB_Command3;
  TCheckBox *ChB_Command3;
  TStaticText *StaticText10;
  TStaticText *StaticText11;
  TEdit *E_Command3_2;
  TGroupBox *GB_Command4;
  TCheckBox *ChB_Command4;
  TStaticText *StaticText12;
  TStaticText *StaticText13;
  TEdit *E_Command4_2;
  TGroupBox *GB_Command5;
  TCheckBox *ChB_Command5;
  TStaticText *StaticText14;
  TStaticText *StaticText15;
  TEdit *E_Command5_2;
  TGroupBox *GB_Command6;
  TCheckBox *ChB_Command6;
  TEdit *E_Command6;
  TGroupBox *GB_Command7;
  TCheckBox *ChB_Command7;
  TComboBox *CB_Command7;
  TScrollBox *SB_Main;
  TGroupBox *GB_Com1;
  TCheckBox *ChB_Com1;
  TComboBox *CB_Com1;
  TGroupBox *GB_Com2;
  TCheckBox *ChB_Com2;
  TEdit *E_Com2;
  TGroupBox *GB_Com3;
  TStaticText *StaticText16;
  TStaticText *StaticText17;
  TEdit *E_Com3_1;
  TEdit *E_Com3_2;
  TGroupBox *GB_Com4;
  TCheckBox *ChB_Com4;
  TStaticText *StaticText18;
  TStaticText *StaticText19;
  TEdit *E_Com4_1;
  TEdit *E_Com4_2;
  TGroupBox *GB_Com5;
  TCheckBox *ChB_Com5;
  TStaticText *StaticText20;
  TStaticText *StaticText21;
  TEdit *E_Com5_1;
  TEdit *E_Com5_2;
  TGroupBox *GB_Com6;
  TCheckBox *ChB_Com6;
  TComboBox *CB_Com6;
  TGroupBox *GB_Com7;
  TCheckBox *ChB_Com7;
  TComboBox *CB_Com7;
  TCheckBox *ChB_Com3;
  TGroupBox *GB_Com8;
  TCheckBox *ChB_Com8;
  TComboBox *CB_Com8;
  TGroupBox *GB_Com9;
  TCheckBox *ChB_Com9;
  TComboBox *CB_Com9;
  TGroupBox *GB_Com10;
  TCheckBox *ChB_Com10;
  TComboBox *CB_Com10;
  TStaticText *StaticText22;
  TGroupBox *GB_Com11;
  TCheckBox *ChB_Com11;
  TComboBox *CB_Com11;
  TStaticText *StaticText23;
  TGroupBox *GB_Com12;
  TCheckBox *ChB_Com12;
  TComboBox *CB_Com12;
  TStaticText *StaticText24;
  TGroupBox *GB_Com13;
  TCheckBox *ChB_Com13;
  TEdit *E_Com13_1;
  TStaticText *StaticText25;
  TEdit *E_Com13_2;
  TStaticText *StaticText26;
  TEdit *E_Com13_3;
  TStaticText *StaticText27;
  TGroupBox *GB_Com14;
  TCheckBox *ChB_Com14;
  TEdit *E_Com14_1;
  TStaticText *StaticText28;
  TEdit *E_Com14_2;
  TStaticText *StaticText29;
  TEdit *E_Com14_3;
  TStaticText *StaticText30;
  TGroupBox *GB_Com15;
  TCheckBox *ChB_Com15;
  TEdit *E_Com15_1;
  TStaticText *StaticText31;
  TEdit *E_Com15_2;
  TStaticText *StaticText32;
  TEdit *E_Com15_3;
  TStaticText *StaticText33;
  TGroupBox *GB_Com16;
  TCheckBox *ChB_Com16;
  TEdit *E_Com16_1;
  TStaticText *StaticText34;
  TEdit *E_Com16_2;
  TStaticText *StaticText35;
  TEdit *E_Com16_3;
  TStaticText *StaticText36;
  TGroupBox *GB_Com17;
  TCheckBox *ChB_Com17;
  TEdit *E_Com17_1;
  TStaticText *StaticText37;
  TEdit *E_Com17_2;
  TStaticText *StaticText38;
  TEdit *E_Com17_3;
  TStaticText *StaticText39;
  TGroupBox *GB_Com18;
  TCheckBox *ChB_Com18;
  TEdit *E_Com18_1;
  TStaticText *StaticText40;
  TEdit *E_Com18_2;
  TStaticText *StaticText41;
  TEdit *E_Com18_3;
  TStaticText *StaticText42;
  TGroupBox *GB_Com19;
  TCheckBox *ChB_Com19;
  TEdit *E_Com19_1;
  TStaticText *StaticText43;
  TEdit *E_Com19_2;
  TStaticText *StaticText44;
  TEdit *E_Com19_3;
  TStaticText *StaticText45;
  TGroupBox *GB_Com20;
  TCheckBox *ChB_Com20;
  TEdit *E_Com20_1;
  TStaticText *StaticText46;
  TEdit *E_Com20_2;
  TStaticText *StaticText47;
  TEdit *E_Com20_3;
  TStaticText *StaticText48;
  TMemo *M_Debug;
  TEdit *E_Command3_0;
  TStaticText *StaticText49;
  TComboBox *CB_Command3_1;
  TComboBox *CB_Command4_1;
  TComboBox *CB_Command5_1;
  void __fastcall SB_OnOffClick(TObject *Sender);
  void __fastcall SystemTimerTimer(TObject *Sender);
  void __fastcall WorkTimerTimer(TObject *Sender);
  void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
  void __fastcall FormCreate(TObject *Sender);
  void __fastcall B_EnterClick(TObject *Sender);
  void __fastcall TB_LoadBlpClick(TObject *Sender);
  void __fastcall TB_LoadSarClick(TObject *Sender);
  void __fastcall B_AddBTClick(TObject *Sender);
  void __fastcall B_DeleteBTClick(TObject *Sender);
  void __fastcall B_AddSar1Click(TObject *Sender);  
  void __fastcall B_DeleteSar1Click(TObject *Sender);
  void __fastcall B_AddSar2Click(TObject *Sender);
  void __fastcall B_DeleteSar2Click(TObject *Sender);
  void __fastcall B_AddSar3Click(TObject *Sender);
  void __fastcall B_AddSar4Click(TObject *Sender);
  void __fastcall B_DeleteSar3Click(TObject *Sender);
  void __fastcall B_DeleteSar4Click(TObject *Sender);
  void __fastcall TB_ExitClick(TObject *Sender);
  void __fastcall RB_ControlClick(TObject *Sender);
  void __fastcall RB_TestingClick(TObject *Sender);
  void __fastcall FormShow(TObject *Sender);
  void __fastcall LVScanDblClick(TObject *Sender);
  void __fastcall LV_Sar1DblClick(TObject *Sender);
  void __fastcall LV_Sar2DblClick(TObject *Sender);
  void __fastcall LV_Sar3DblClick(TObject *Sender);
  void __fastcall LV_Sar4DblClick(TObject *Sender);
  void __fastcall B_ReadyClick(TObject *Sender);
  void __fastcall CB_Command1Change(TObject *Sender);
  void __fastcall E_Command3_0KeyPress(TObject *Sender, char &Key);
  void __fastcall E_Command3_0Exit(TObject *Sender);
  void __fastcall CB_Command3_1Change(TObject *Sender);
  void __fastcall CB_Command4_1Change(TObject *Sender);
  void __fastcall CB_Command5_1Change(TObject *Sender);
private:	// User declarations
  AnsiString BlpFName;
  AnsiString SarFName;
public:		// User declarations
  void __fastcall TMain_Form::AddSaveLog(AnsiString comment);
  void __fastcall TMain_Form::Update_Dump_blp();
  void __fastcall TMain_Form::Update_Dump_sar();
  bool TMain_Form::IsValidInt(int min, int max, String value, String EdIzm);
  void TMain_Form::ShowError(int ErrorNum, float Par1, float Par2, String Par3);
  AnsiString My_Patch;
  AnsiString logFname;
  __fastcall TMain_Form(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TMain_Form *Main_Form;
//---------------------------------------------------------------------------
#endif
